### ISSUE TITLE
`nimble install` fails on Windows because of missing CA certificates

### ISSUE THREAD

**Issue by markspanbroek** [iffy/install-nim#11]
Example run:

```
Run nimble install -y
  nimble install -y
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  Verifying dependencies for quic@0.1.0
    Prompt: No local packages.json found, download it from internet? -> [forced yes]
Downloading Official package list
       Tip: 6 messages have been suppressed, use --verbose to show them.
     Error: Refresh failed
        ... Could not download: No SSL/TLS CA certificates found.
Error: Process completed with exit code 1.
```

Workflow file:

```yaml
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v3
    - name: Build
      run: nimble install -y
    - name: Test
      run: nimble test -y
```

**Comment by iffy** [comment]
I'm trying to figure out what's going wrong.  I think this is an upstream problem with choosenim, and maybe even more upstream with the new Nim version (1.4.4)? Here are some related discussions:

- https://github.com/dom96/choosenim/issues/251
- https://forum.nim-lang.org/t/7494

Does the build succeed if you use the following?

```yaml
- uses: iffy/install-nim@v3
   with:
     version: 1.4.2
```
