### ISSUE TITLE
Why is it so slow on macOS?

### ISSUE THREAD

**Issue by bichanna** [iffy/install-nim#20]
Hi there.

I'm using install-nim in my project, and I found that your Github Action is very slow on macOS (though, it's fast on Ubuntu).
```
jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v3.2.2
        with:
          version: stable
 ...
```
<img width="1012" alt="Screen Shot 2022-03-12 at 1 16 45 AM" src="https://user-images.githubusercontent.com/60306074/158008227-acb45a01-d29a-4aa4-ac40-51974ccab3df.png">
As you can see above, it took 9 minutes.

Is there a way of speeding it up?
